#!/bin/bash
for i in $(find -name "*.[hc]")
do
	exec > tmp

	# new header (end of this script)
	tail -n17 $0
	echo ""

	# length of the old header
	line=`grep -Enm1 '^\\\\\*/$' $i`
	line=${line%%:\\*/}
	line=${line:--1}
	line=$(($line+2))

	# skip the old header
	tail $i -n+$line

	mv tmp $i
done
exit 0
/*\
 *  Yes, This Is Another Barcode Reader
 *  Copyright (C) 2013 Quentin SANTOS
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
\*/
